// examples/react-demo/src/components/PivotTable.tsx
import { useEffect, useRef, useMemo } from "react";
import { createPivotUI } from "@jmars25/pivottable-ts/vanilla";
import type { PivotUIOptions } from "@jmars25/pivottable-ts/vanilla";

// ─── usePivotUI ──────────────────────────────────────────────────────────────
// Core hook: mounts a pivot UI into a div, cleans up on unmount or locale change.

function usePivotUI(data: unknown, opts: PivotUIOptions, locale: string) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const handle = createPivotUI(el, data, opts, /* overwrite */ true, locale);
    return () => handle.destroy();
  }, [data, opts, locale]);

  return ref;
}

// ─── PivotTable ──────────────────────────────────────────────────────────────

interface PivotTableProps {
  data:         unknown[];
  locale?:      string;
  renderers?:   PivotUIOptions["renderers"];
  rendererName?: string;
  rows?:        string[];
  cols?:        string[];
  vals?:        string[];
}

export default function PivotTable({
  data,
  locale        = "en",
  renderers,
  rendererName,
  rows          = [],
  cols          = [],
  vals          = [],
}: PivotTableProps) {
  const opts = useMemo<PivotUIOptions>(() => ({
    renderers,
    rendererName,
    rows,
    cols,
    vals,
  }), [renderers, rendererName, rows, cols, vals]);

  const ref = usePivotUI(data, opts, locale);

  return <div ref={ref} style={{ width: "100%" }} />;
}

// examples/vue-demo/src/components/PivotTable.vue
<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { type PivotUIOptions } from "@jmars25/pivottable-ts/vanilla";
import { usePivotUI } from "../composables/usePivotUI";

// ─── Props ────────────────────────────────────────────────────────────────────

const props = withDefaults(
  defineProps<{
    data: unknown[];
    locale?: string;
    renderers?: Record<string, unknown>;
    rendererName?: string;
    rows?: string[];
    cols?: string[];
    vals?: string[];
  }>(),
  { locale: "en" },
);

// ─── Reactive refs passed into the composable ─────────────────────────────────

const localeRef = computed(() => props.locale);

const dataRef = computed(() => props.data);

/**
 * Build opts from current props. We do NOT include aggregatorName so that
 * locale switching can't break the aggregator dropdown (same fix as React demo).
 */
const optsRef = computed<PivotUIOptions>(() => ({
  renderers:    props.renderers,
  rendererName: props.rendererName,
  rows:         props.rows,
  cols:         props.cols,
  vals:         props.vals,
}));

// ─── Mount pivot ──────────────────────────────────────────────────────────────

const containerRef = ref<HTMLDivElement | null>(null);

const { init } = usePivotUI(containerRef, dataRef, optsRef, localeRef);

onMounted(init);
</script>

<template>
  <div ref="containerRef" style="width: 100%" />
</template>
